data:
  # Where to save the demos
  save_path: /tmp/rlbench_data/
  # The size of the images to save
  image_size: [128, 128]
  # The renderer to use. Either opengl or opengl3. The first has no shadows
  renderer: opengl3
  # The number of episodes to collect per task
  episodes_per_task: 5
  # The image types that will be recorded
  images:
    rgb: True
    depth: True
    mask: True
    point_cloud: True
  # The cameras that we will be enabled
  cameras:
    left_shoulder: True
    right_shoulder: True
    overhead: True
    wrist: True
    front: True
  # Store depth as 0 - 1
  depth_in_meters: False
  # We want to save the masks as rgb encodings.
  masks_as_one_channel: True
env:
  task_name: "basketball_in_hoop"
  seed: 42
  scene:
    factors:

      - variation: object_color
        name: manip_obj_color
        enabled: False
        targets: [ball]
        seed: ${env.seed}

      - variation: object_color
        name: recv_obj_color
        enabled: False
        targets: [basket_ball_hoop_visual]
        seed: ${env.seed}

      - variation: object_texture
        name: manip_obj_tex
        enabled: False
        targets: [ball]
        mapping_mode: 2
        seed: ${env.seed}

      - variation: object_texture
        name: recv_obj_tex
        enabled: False
        targets: [basket_ball_hoop_visual]
        seed: ${env.seed}

      - variation: object_size
        name: manip_obj_size
        enabled: False
        targets: [ball]
        scale_range: [0.75, 1.25]
        seed: ${env.seed}

      - variation: object_size
        name: recv_obj_size
        enabled: False
        targets: [basket_ball_hoop_respondable]
        scale_range: [0.75, 1.15]
        seed: ${env.seed}

      - variation: light_color
        enabled: False
        targets: [DefaultLightA, DefaultLightB, DefaultLightD]
        color_range: [[0.0, 0.0, 0.0], [0.5, 0.5, 0.5]]
        seed: ${env.seed}

      - variation: table_texture
        enabled: False
        seed: ${env.seed}

      - variation: table_color
        enabled: False
        color_range: [[0.25, 0.25, 0.25], [1.0, 1.0, 1.0]]
        seed: ${env.seed}

      - variation: background_texture
        enabled: False
        seed: ${env.seed}

      - variation: distractor_object
        enabled: False
        targets: [spawn_boundary0]
        num_objects: 2
        seed: ${env.seed}

      - variation: distractor_object
        enabled: False
        targets: [spawn_boundary1]
        num_objects: 2
        seed: "${eval: '${env.seed} + 1'}"

      - variation: camera_pose
        enabled: False
        targets: [cam_front,
                  cam_over_shoulder_left,
                  cam_over_shoulder_right]
        euler_range: [[-0.05, -0.05, -0.05], [0.05, 0.05, 0.05]]
        position_range: [[-0.1, -0.1, -0.1], [0.1, 0.1, 0.1]]
        seed: ${env.seed}
